# Generated by Django 5.0 on 2023-12-05 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('nome', models.CharField(max_length=255)),
                ('tel', models.IntegerField()),
                ('nascimento', models.DateField()),
                ('medico', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('usuario_ptr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='medico_usuario', serialize=False, to='membros.usuario')),
            ],
            bases=('membros.usuario',),
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='membros.usuario')),
                ('sintomas', models.CharField(max_length=255)),
                ('dataDeEntrada', models.DateField()),
                ('medicoResponsavel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='membros.medico')),
            ],
            bases=('membros.usuario',),
        ),
    ]
