# Generated by Django 4.2.8 on 2023-12-07 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='dataDeEntrada',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='sintomas',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
