# Generated by Django 4.2.8 on 2023-12-11 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('membros', '0002_alter_customuser_medico_alter_customuser_nascimento_and_more'),
        ('membros', '0002_alter_paciente_datadeentrada_alter_paciente_sintomas'),
        ('membros', '0003_rename_user_customuser'),
    ]

    operations = [
    ]
