# Generated by Django 4.2.8 on 2023-12-11 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membros', '0004_merge_20231211_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='doente',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
