# Generated by Django 4.2.9 on 2024-01-20 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membros', '0006_paciente_status_paciente_tratamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='historicoTratamentos',
            field=models.JSONField(null=True),
        ),
    ]
