# Generated by Django 4.2.9 on 2024-01-20 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membros', '0007_paciente_historicotratamentos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='tratamento',
            field=models.CharField(default='Aguardando tratamento!', max_length=255, null=True),
        ),
    ]
