# Generated by Django 4.2.9 on 2024-01-20 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membros', '0009_alter_paciente_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='historicoTratamentos',
            field=models.JSONField(default={}, null=True),
        ),
    ]
